
schemaName: sharding_db

dataSourceCommon:
 username: root
 password:
 connectionTimeoutMilliseconds: 30000
 idleTimeoutMilliseconds: 60000
 maxLifetimeMilliseconds: 1800000
 maxPoolSize: 5
 minPoolSize: 1
 maintenanceIntervalMilliseconds: 30000

dataSources:
  test_0: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/test_0
    username: root
    password: root
    autoCommit: false
  test_1: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/test_1
    username: root
    password: root
    autoCommit: false

rules:
  - !SHARDING
    tables:
      order:
        actualDataNodes: test_${0..1}.order_${0..15}
        databaseStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: database_inline
        tableStrategy:
          standard:
            shardingColumn: order_id
            shardingAlgorithmName: order_inline
    bindingTables:
      - order

    shardingAlgorithms:
      database_inline:
        type: INLINE
        props:
          algorithm-expression: test_${id % 2}
      order_inline:
        type: INLINE
        props:
          algorithm-expression: order_${order_id % 15}

props:
  sql-show: true